"""add created_at updated_at

Revision ID: 61c7cfb6b836
Revises: 
Create Date: 2026-06-11 12:31:53.551008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c7cfb6b836'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('cars', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cars', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.alter_column('cars', 'desc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('cars', 'updated_at')
    op.drop_column('cars', 'created_at')
    # ### end Alembic commands ###
